### ISSUE TITLE
Catalyst Milestone 1: Setup and Test Suite

### ISSUE THREAD

**Issue by itsfarseen** [mlabs-haskell/cardano-dev-wallet#7]
# Outputs

- [x] An installable browser extension for Chromium-based browsers and Firefox.  
  [milestone-1.zip](https://github.com/mlabs-haskell/cardano-dev-wallet/files/13417666/milestone-1.zip)
  
- [x] A link to a Github commit containing the source code from which the project can be built:
  https://github.com/mlabs-haskell/cardano-dev-wallet/commit/7f406c53e859090a4cf8e74921d0e37f24258162
- [x] Automated test-suite:
  https://github.com/mlabs-haskell/cardano-dev-wallet/blob/master/webext/tests/example.spec.js
  
  Running: 
  ```
  cd webext
  just setup # Install node packages
  npx playwright install # Install browsers for playwright
  just test chrome # Run tests
  ```
  
- [x] Video demonstration show casing the test-case execution. 

  The recording from the automated test-suite:
  (The video is short because the tests finish too fast)
[b4a20e927fd57a9580fe76def24a0af7.webm](https://github.com/mlabs-haskell/cardano-dev-wallet/assets/40014472/e454f4f4-92c5-41de-b382-5650c0bef5b4)

  Recording of manual testing:
[video.webm](https://github.com/mlabs-haskell/cardano-dev-wallet/assets/40014472/4166ba84-4ebc-458f-a4a8-0cca45ee9968)
